import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const links = [{
  label: 'Home',
  route: '/'
},{
  label: 'Projects',
  route: '/projects'
  }
] 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <title>My first nextjs app</title>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
